AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Cloud12:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5eff06f840b45e9
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: Git Sync
